config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'tops#index'
  get 'home/about' => "tops#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :index]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
    validates :body, presence: true
    validates :body, length: {maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, length: {maximum:20}
  validates :name, length: {minimum:2}
  validates :introduction, length: {maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  	  user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
  	  user_path(current_user.id)
  end


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :colect_user, only:[:edit, :update]

  def index
  	  @user = current_user
  	  @book = Book.new
  	  @books = Book.all
  end
  def show
  	  @book = Book.find(params[:id])
  	  @newbook = Book.new
  end
  def create
  	  @book = Book.new(book_params)
  	  @book.user_id = current_user.id
  	  if @book.save
  	     flash[:notice] = "You have creatad book successfully."
  	     redirect_to book_path(@book.id)
  	  else
  	  	 @user = current_user
	  	 @books = Book.all
  	  	 render action: :index
  	  end
  end
  def edit
  	  @book = Book.find(params[:id])
  end
  def update
  	  @book = Book.find(params[:id])
  	  if @book.update(book_params)
  	  	flash[:notice] = "You have updated book successfully."
  	  	redirect_to book_path(@book.id)
  	  else
  	  	@books = Book.all
  	  	render action: :edit
  	  end
  end
  def destroy
  	  book = Book.find(params[:id])
  	  book.destroy
  	  redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end
  def colect_user
  	 @book = Book.find(params[:id])
 	 if @book.user_id != current_user.id
 	    redirect_to books_path
 	 end
 end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   before_action :colect_user, only: [:edit, :update]

  def show
  	  @user = User.find(params[:id])
  	  @book = Book.new
  	  @books = @user.books
  end
  def update
  	  @user = User.find(params[:id])
  	  if @user.update(user_params)
  	     flash[:notice] = "You have updated user successfully."
  	     redirect_to user_path(@user.id)
  	  else
  	  	@users = User.all
  	  	render action: :edit
  	  end
  end
  def index
  	  @users = User.all
  	  @book = Book.new
  end
  def new
  	  @user = Book.new
  	  @user = User.new
  end

  def edit
  end

  def create
  	  @user = User.new(user_params)
  	  @user.save
  	  flash[:notice] = "Welcome! You have signed up successfully."
  	  redirect_to @user
  end

    private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end

	def colect_user
	 @user = User.find(params[:id])
 	 if @user.id != current_user.id
 	    redirect_to user_path(current_user)
 	 end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="top-message col_md-offset-3 col-md-3">
	<h1>EditingBook</h1>

	<%= form_for(@book) do |f| %>
		<% if @book.errors.any? %>
		        <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
		        <% @book.errors.full_messages.each do |message| %>
		            <li><%= message %></li>
		        <% end %>
		<% end %>


		  <h4>Title</h4>
		  <%= f.text_field :title %>
		  <h4>Opinion</h4>
		  <%= f.text_field :body %>
		  <%= f.submit 'UpdateBook', class:"btn btn-primary col-xs-12" %>
	<% end %>

		<div>
		  <%= link_to "show", book_path(@book) %>
		  <%= link_to "Back", books_path %>
		</div>
</div>

app/views/books/index.html.erb
<%= render 'users/list' , user: @user, book: @book %>

<div class='container'>
  <div class="col-xs-9">
    <h2>Books</h2>
      <table calss="table table-hover table-inverse">
          <thead>
        		<tr>
        			<th></th>
             	<th>Title</th>
             	<th>Opinion</th>
          	</tr>

        	　<% @books.each do |book| %>
        		<tr>
        			<td>
        				<%= link_to user_path(book.user) do %>
        				<%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', size: '40x40', fallback: "no_image.jpg" %>
        				<% end %>
              </td>

        	  	<td><%= link_to "#{book.title}", book_path(book) %></td>
        	  	<td><%= book.body %></td>
            </tr>
            <% end %>
        	</thead>
      </table>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'users/list', user: @book.user, book: @newbook %>


<h2>Book detail</h2>
  <div class="col-xs-9">
	<table class="table">
		<td>
		 	<%= link_to user_path(@book.user) do %>
		 	<%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %><br>
		 	<%= @book.user.name %>
		 	<% end %>
		</td>
		<td><%= @book.title %></td>
		<td><%= @book.body %></td>

		<td><% if current_user == @book.user %>
			<%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success edit_book_15610" %>
			<%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class:"btn-sm btn-danger destroy_book_15610" %>
		</td>
	 <% end %>
	</table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tag %>
    <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <span class="nav navbar-nav navbar-left">Bookers</span>

       <% if user_signed_in? %>

        <div class= "nav navbar-nav navbar-right">
          <li><%= link_to 'Home', user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>

          <li><%= link_to 'Users', users_path, class: "glyphicon glyphicon-user users" %></li>

          <li><%= link_to 'Books', books_path, class: "glyphicon glyphicon-book books" %></li>

          <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
        </div>

       <% else %>

         <div class= "nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path, class: "glyphicon glyphicon-home home" %></li>

          <li><%= link_to 'About', home_about_path, class: "glyphicon glyphicon-link about" %></li>

          <li><%= link_to 'sign up', new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>

          <li><%= link_to 'login', new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
         </div>
       <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tops/about.html.erb
<h2>
	welcome to <div class="glyphicon glyphicon-book">Bookers !!</div>
</h2>

app/views/tops/index.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<div class="top-message col-md-offset-3 col-md-6">
	<h2>
		welcome to <div class="glyphicon glyphicon-book">Bookers !!</div>
	</h2>
	<p>In<strong class="glyphicon glyphicon-book">Bookers</strong></p>

	<p>you can share and exchange your opinions , inpressions , and emotions</p>
	<p>about various books!</p>

	<div class="btn-wrapper">
		<P><%= link_to "Log in",  new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></P>
		<p><%= link_to "sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %> </p>
    </div>
</div>

app/views/users/_list.html.erb
<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<% if book.errors.any? %>
        <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
        <% book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
<% end %>

    <div class="col-xs-3">
	    <h2>User info</h2>
	    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
		<table class="table">
		  <tbody>
		    <tr>
		  		<td>name</td>
		  		<td><%= user.name %></td>
		  	</tr>
		  	<tr>
		  		<td>introduction</td>
		  		<td><%= user.introduction %></td>
		  	</tr>
		  </tbody>
		</table>
	        <p><%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_9519" %></p>

		<h1>New book</h1>
		<%= form_for(book) do |f| %>

		<h4>Title</h4>
		<%= f.text_field :title %>

		<h4>Opinion</h4>
		<%= f.text_area :body %>

		<%= f.submit 'Create Book',class: "btn btn-primary col-xs-12" %>

		<% end %>
	</div>

app/views/users/edit.html.erb
<h2>User info</h2>


<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<h2><%= @user.errors.count %> errors prohibited this obj
		from being saved:</h2>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
<% end %>

	<div class="form-group has-icon">
		<label class="control-label sr-only" for="inputEmail">Name</label>
		<%= f.text_field :name, autofocus: true, class:"form-control", placeholder:"名前"%>
	</div>
	<div>
		<label>Image</label>
		<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
	</div>
	<div>
		<lavel>Introduction</lavel>
		<%= f.text_area :introduction %>
	</div>



	<%= f.submit "Update User" %>
	<% end %>

app/views/users/index.html.erb
<%= render 'users/list', user: current_user, book: @book %>
<div class="col-xs-9">
  <table class="table">
  	<thead>
    		<h2>Users</h2>
    		<tr>
         		<th>image</th>
         		<th>name</th>
         		<th></th>
      	</tr>
    	</thead>
    	<tbody>
    	　<% @users.each do |user| %>
    		<tr>
    			<td>
    				<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', size: '40x40', fallback: "no_image.jpg" %>
    			</td>
    	  		<td><%= user.name %></td>
    	  		<td>
    	  			<%= link_to "show", user_path(user) %>
    	  		</td>
    		</tr>
    	   <% end %>
    	</tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'users/list', user:@user, book: @book %>
  <div class="col-xs-9">
    <table class="table table-hover table-inverse">
    	<thead>
      		<h2>Books</h2>
        		<tr>
        			<th></th>
             		<th>Title</th>
             		<th>Opinion</th>
          	</tr>
      </thead>
      	<tbody>
      	 <% @books.each do |book| %>
      		<tr>
      			<td>
    	  			<%= link_to user_path(book.user) do %>
    				  <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', size: '40x40', fallback: "no_image.jpg" %>
            </td>
    			<% end %>
      			<td><%= link_to book.title, book_path(book) %></td>
      	  		<td><%= book.body %></td>
      		</tr>
      	 <% end %>
      	</tbody>
    </table>
  </div>